import { Metadata } from "next";
import { buildLangAlternates } from "@/lib/seo";

interface Props {
  params: Promise<{ lang: string }>;
}

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const { lang } = await params;
  const isEs = lang === "es";
  const title = isEs ? "Aviso Legal" : "Disclaimer";
  const description = isEs
    ? "Aviso legal de AI Peak Biz sobre ganancias, resultados y uso de nuestro sitio web y servicios."
    : "AI Peak Biz disclaimer regarding earnings, results, and use of our website and services.";
  const url = isEs
    ? "https://www.aipeakbiz.com/es/disclaimer"
    : "https://www.aipeakbiz.com/disclaimer";

  return {
    title,
    description,
    alternates: buildLangAlternates(lang, "/disclaimer"),
    openGraph: {
      title: `${title} | AI Peak Biz`,
      description,
      url,
    },
  };
}

export default function DisclaimerPage() {
  return (
    <section className="section-padding pt-32 md:pt-40">
      <div className="container-custom max-w-3xl">
        <h1 className="text-3xl md:text-4xl font-bold text-text-primary tracking-display mb-8">
          Disclaimer
        </h1>
        <div className="prose prose-invert prose-sm max-w-none space-y-6 text-text-secondary">
          <p><strong className="text-text-primary">Last Updated:</strong> April 20, 2026</p>

          <h2 className="text-xl font-bold text-text-primary mt-8">General Disclaimer</h2>
          <p>The information provided on the AI Peak Biz website (aipeakbiz.com) is for general informational purposes only. While we strive to keep the information up to date and accurate, we make no representations or warranties of any kind, express or implied, about the completeness, accuracy, reliability, suitability, or availability of the information, products, services, or related graphics contained on the website.</p>

          <h2 className="text-xl font-bold text-text-primary mt-8">Earnings and Results Disclaimer</h2>
          <p>Any revenue figures, ROI estimates, cost savings, or financial projections mentioned on this website, in our marketing materials, or generated by our Free Assessment tool are estimates only. They are based on industry averages and general assumptions. Your actual results will vary depending on your business, market, location, effort, and many other factors beyond our control.</p>
          <p>We do not guarantee any specific level of revenue increase, cost savings, or business results from using our services. Past performance of our clients does not guarantee future results for your business.</p>

          <h2 className="text-xl font-bold text-text-primary mt-8">Free Assessment Tool Disclaimer</h2>
          <p>The Free Assessment tool on our website provides estimated revenue loss calculations based on the data you input and general industry assumptions. These estimates are not financial advice and should not be relied upon as the sole basis for business decisions. The calculations use industry-average conversion rates and benchmarks that may not reflect your specific business situation.</p>

          <h2 className="text-xl font-bold text-text-primary mt-8">Testimonials Disclaimer</h2>
          <p>Testimonials displayed on our website are from real clients and represent their individual experiences. These testimonials are not intended to represent or guarantee that current or future clients will achieve the same or similar results. Each client&apos;s experience and results depend on many factors specific to their business.</p>

          <h2 className="text-xl font-bold text-text-primary mt-8">Third-Party Links</h2>
          <p>Our website may contain links to third-party websites or services that are not owned or controlled by AI Peak Biz. We have no control over and assume no responsibility for the content, privacy policies, or practices of any third-party websites or services.</p>

          <h2 className="text-xl font-bold text-text-primary mt-8">Professional Advice</h2>
          <p>Nothing on this website constitutes legal, financial, medical, or other professional advice. You should consult with appropriate professionals before making business decisions based on any information provided on this website.</p>

          <h2 className="text-xl font-bold text-text-primary mt-8">Contact</h2>
          <p>
            AI Peak Biz<br />
            Kingman, Arizona<br />
            Email: <a href="mailto:wylie@aipeakbiz.com" className="text-brand hover:underline">wylie@aipeakbiz.com</a><br />
            Phone: <a href="tel:9286286080" className="text-brand hover:underline">928-628-6080</a>
          </p>
        </div>
      </div>
    </section>
  );
}
